### ISSUE TITLE
Insecure deployment of Consul clients for service mesh use case on ECS/Fargate 

### ISSUE THREAD

**Issue by devarshishah3** [hashicorp/consul-ecs#13]
#### Description
Allow **ECS** user to deploy **Consul clients** as a part of a single Consul datacenter within a single AWS region **insecurely ( No ACLs, No TLS, No gossip encryption)** using **Terraform** on **Fargate** launch type. One Consul client should be running per ECS Task along with a sidecar Envoy proxy to enable the service mesh use case. 

#### Use Cases
* This feature would enable communication fully encrypted between ECS tasks with mTLS and prevents potential attackers from sniffing plain-text traffic. In addition, because requests flow through sidecar proxies, Consul can block requests from unauthorized services.enable a true multi-platform service mesh that supports all runtimes.

#### Alternative Solutions
* Users can build their custom deployments for Consul on ECS for different launch types but the user experience is inconsistent and tedious.  

#### Additional context
* Insecure deployment should be recommended for **non-production** environments only

**Comment by lkysow** [comment]
Released as part of tech preview.
