### ISSUE TITLE
Terminating Gateway Support

### ISSUE THREAD

**Issue by reskin89** [hashicorp/consul-ecs#136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Describe the bug

Not sure if a bug, or if I'm missing something.  I cannot seem to figure out how to provide terminating gateway configuration in `CONSUL_ECS_CONFIG_JSON` as I can't seem to find documentation for the proper json to provide? 

Currently I'm trying something like:

```json
{
    "bootstrapDir": "/boot",
    "gateway":  {
        "kind": "terminating-gateway",
        "name": "sometg",
        "services": [
            {
                "name": "myservice",
                "cafile": "/consul/consul-ca-cert.pem",
                "sni":"mysni.com"
            }
        ]
      },
    "proxy" : {
        "config": {
            "max_inbound_connections": 2048
        },
        "publicListenerPort": 21000
    }
  }
```

Mainly I can't seem to see if a `proxy` configuration like this to override the listening port is proper, and it doesn't seem there's anywhere documented for the `services` array in json for a config file, as usually when `POST`ing to the API each json attribute has capital letters, and in a config.json it would be lowercase, but I don't see that at this doc:

https://developer.hashicorp.com/consul/docs/connect/config-entries/terminating-gateway

is this the proper json for a terminating gateway config if being used with `mesh-init`?

### Platform and version information

* `consul-ecs` version: 0.5.2
* Consul version: 1.13.6
* Envoy version: 1.21.5
* ECS launch type (e.g. FARGATE, EC2): Fargate
* Deployment tool and version (e.g. Consul ECS Terraform Module, AWS CDK, etc): For now, flat task-definition.json upload, will be applied to terraform.

**Comment by reskin89** [comment]
Thanks @cthain, is adding terminating and ingress gateway support high on the priority list for this particular deployment support methodology? I use them pretty frequently

**Comment by Ganeshrockz** [comment]
@reskin89 Both terminating gateways and API gateways are now added to ECS. We have published a release candidate for both the ECS binary and the TF module. Feel free to try the same and provide feedback

https://github.com/hashicorp/consul-ecs/releases/tag/v0.8.0-rc1
https://github.com/hashicorp/terraform-aws-consul-ecs/releases/tag/v0.8.0-rc1
