### ISSUE TITLE
Development mode only Consul Server on ECS/Fargate

### ISSUE THREAD

**Issue by devarshishah3** [hashicorp/consul-ecs#14]
#### Description
Allow ECS user to deploy a single **Consul Server** as a part of a single Consul datacenter within a single AWS region insecurely ( No ACLs, No TLS, No gossip encryption) using Terraform on Fargate launch type. This Consul server should be used for **development environments only**. 

#### Use Cases
Consul servers are generally I/O bound for writes because the underlying Raft log store performs a sync to disk every time an entry is appended. Fargate launch type supports Elastic File Storage (EFS) only, which may not support the I/O requirements for Consul Servers in production at scale. But users still need a Consul server to easily realize the value of Consul service mesh on ECS/Fargate for development purposes only.  

#### Alternative Solutions
* Consul servers running on EC2 instances 
* HCP Consul (Consul servers managed by HashiCorp)

#### Additional context
* Recommend Consul Server on ECS/Fargate for development (dev) purposes only

**Comment by lkysow** [comment]
Was released as part of tech preview.
