### ISSUE TITLE
Compatibility with Consul-Dataplane

### ISSUE THREAD

**Issue by reskin89** [hashicorp/consul-ecs#142]
#### Description
Is mesh-init compatible with dataplane?  If not, is there somewhere I can be pointed to see the recommended ECS pattern for using dataplane?

**Comment by reskin89** [comment]
The dataplane docs [here](https://developer.hashicorp.com/consul/docs/v1.14.x/connect/dataplane#feature-support) states that there's ECS support for consul-dataplane as of 1.14 already.  I presume you're specifically stating the mesh-init mechanism doesn't support dataplane?

**Comment by pglass** [comment]
Oh, I guess you are referring to the Fargate support? Consul Dataplane is only currently supported in Kubernetes (consul-k8s) so the Fargate support is for EKS Fargate (not ECS Fargate).

**Comment by reskin89** [comment]
ah thank you for the information! that makes sense
