### ISSUE TITLE
Support gossip traffic encryption between Consul agents

### ISSUE THREAD

**Issue by devarshishah3** [hashicorp/consul-ecs#15]
#### Description
Allow users to enable gossip traffic encryption between Consul agents 

#### Use Cases
This capability will enable users to deploy and operate a Consul cluster on ECS in a secure manner.

#### Additional context
Enabling gossip encryption should recommended for all production Consul deployments on ECS

**Comment by lkysow** [comment]
Released in beta1.

**Comment by tine-s** [comment]
Hello team,

I was wondering if you guys have already a date when Consul Service mesh for ECS Fargate will be released for production workload?
I am asking as we're in the middle of a project in which we are really keen to use the Consul Service Mesh for ECS Fargate which would allow us to maintain the sticky session.

Thank you In advance,
Tinè

**Comment by pglass** [comment]
Hi @tine-s,

Thanks for your interest! Our GA release is next week, Nov 17. That release will be ready for production workloads.

**Comment by ushakkodali** [comment]
Hi @tine-s ,

Consul on ECS team is gathering feedback on usecases. Wondering if you would be willing to discuss more on this in a e-meeting ? 

Also as @pglass mentioned, we are planning on releasing production ready image next week.
Thanks,
Usha
