### ISSUE TITLE
Support configuring ACLs on Consul clients on ECS  

### ISSUE THREAD

**Issue by devarshishah3** [hashicorp/consul-ecs#17]
#### Description
Allow users to enable and configure Consul ACLs systems for Consul clients, services and UI.

#### Use Cases
Consul uses Access Control Lists (ACLs) to secure access to the UI, API, CLI, service communications, and agent communications. This feature will enable deploying Consul securely on ECS for production environments. 

#### Additional context
Enabling ACL systems should recommended for all production Consul deployments on ECS

**Comment by lkysow** [comment]
Released in beta1.
