### ISSUE TITLE
BootstrapDir not set using environment variable

### ISSUE THREAD

**Issue by jameshiester** [hashicorp/consul-ecs#55]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Describe the bug

ECS shows error "-envoy-bootstrap-dir must be set" when running task.

### Platform and version information

* `consul-ecs` version: 0.2.0
* Consul version: 1.10.4
* Envoy version: v1.18.4
* ECS launch type (e.g. FARGATE, EC2): Fargate
* Deployment tool and version (e.g. Consul ECS Terraform Module, AWS CDK, etc):
ECS Terraform Module (running from windows machine)

### Reproduction Steps

1. Environment variable CONSUL_ECS_CONFIG_JSON is set to: {"bootstrapDir":"/consul","proxy":{"upstreams":[]},"service":{"checks":[{"checkId":"server-http","http":"http://localhost:443/api/tsp/v1/health","interval":"5s","method":"GET","name":"HTTP health check","timeout":"10s"}],"name":"dev-tsp-api","port":443}}
2. Using the default volume mount for consul_data to /consul
3. Using default mesh-init start command

### Expected behavior

The container should run successfully without error.

**Comment by pglass** [comment]
Hi @jameshiester,

> consul-ecs version: 0.2.0

This version does not support the new `CONSUL_ECS_CONFIG_JSON` environment variable.

I'd recommend using version [`v0.2.0`](https://github.com/hashicorp/terraform-aws-consul-ecs/releases/tag/v0.2.0) of the Consul ECS Terraform module, which is the latest release.

**Comment by jameshiester** [comment]
There’s a difference between 0.2.0 and v0.2.0? Maybe you need to publish a new docker image, dockerhub reports the latest tag as 4 months old and 0.2.0 is 2 months.

**Comment by lkysow** [comment]
Hey sorry for the confusion. What paul was saying is that support for the `CONSUL_ECS_CONFIG_JSON` isn't released yet. We're guessing that you're running into this issue because you're using the Terraform module off of `main` instead of the `v0.2.0` tag.

**Comment by jameshiester** [comment]
Thank you.  Please close this issue, but first, should this module support adding a client cert/key for tls?

**Comment by lkysow** [comment]
Currently the module only supports auto-encrypt (https://learn.hashicorp.com/tutorials/consul/tls-encryption-secure#client-certificate-distribution) which means Consul servers will send the clients their certificates.
