### ISSUE TITLE
consul-ecs:0.3.0 seems to be borked in ECR Public Gallery

### ISSUE THREAD

**Issue by polewskm** [hashicorp/consul-ecs#64]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request. Searching for pre-existing feature requests helps us consolidate datapoints for identical requirements into a single place, thank you!
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Describe the bug

Something seams to be wrong with the currently posted image at:
`public.ecr.aws/hashicorp/consul-ecs:0.3.0`

Fargate is reporting the following error:
`CannotPullContainerError failed to find a descriptor for platform 0xc0004d52c0 0xc0004d5320`

When attempting to inspect the image locally, I get the following:
```
docker image pull public.ecr.aws/hashicorp/consul-ecs:0.3.0
docker image inspect public.ecr.aws/hashicorp/consul-ecs:0.3.0
```

Response:
```
0.3.0: Pulling from hashicorp/consul-ecs
no matching manifest for linux/amd64 in the manifest list entries
```

What is weird is that the `latest` image tag is fine and I see its architecture as linux amd64:
```
docker image pull public.ecr.aws/hashicorp/consul-ecs:latest
docker image inspect public.ecr.aws/hashicorp/consul-ecs:latest
```

### Platform and version information

* `consul-ecs` version: 0.3.0
* Consul version: n/a
* Envoy version:  n/a
* ECS launch type (e.g. FARGATE, EC2): FARGATE
* Deployment tool and version (e.g. Consul ECS Terraform Module, AWS CDK, etc): While using your mesh-task terraform module

### Reproduction Steps

```
docker image pull public.ecr.aws/hashicorp/consul-ecs:0.3.0
docker image inspect public.ecr.aws/hashicorp/consul-ecs:0.3.0
```

### Expected behavior

I expect to see the following:
```
        "Architecture": "amd64",
        "Os": "linux",
```

### Additional context

I did notice that the image has been recently updated.

**Comment by pglass** [comment]
Hi @polewskm, thanks the report! I'm not currently able to reproduce this. Are you still seeing this issue?

We've looked into this internally. We use a process that periodically syncs images from [Docker Hub](https://hub.docker.com/r/hashicorp/consul-ecs/tags) to ECR. We believe the images in ECR were resynced due to a bug in that process, and during a resync of an image you can see brief unavailability of the image, which you saw. Apologies. We'll soon be switching away from this process to avoid this issue in the future.

**Comment by polewskm** [comment]
I can confirm that I am now able to successfully pull down the image in Fargate and locally. I also see that the image in ECR was updated after I posted this issue. So I probably ran into the issue you just mentioned. We can close this ticket.
